
// This file has been generated by the GUI designer. Do not modify.

public partial class StreamingWindow
{
    protected virtual void Build()
    {
        global::Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "StreamingWindow";
        this.Title = global::Mono.Unix.Catalog.GetString("StreamingWindow");
        this.WindowPosition = ((global::Gtk.WindowPosition)(5));
        if ((this.Child != null))
        {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 600;
        this.DefaultHeight = 500;
        this.Show();
        this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}